/* sound_mega65.c - Audio DMA playback of the packed SFX blob.
 *
 * The blob (DAGGOR65.SFX, unsigned 8-bit, 7350 Hz - see sfx_index65.h,
 * generated by tools/gen_sfxbin.py from assets/raw-7350) is streamed
 * at init through hyppo file reads (mega65-libc fileio.s) into free
 * chip RAM and played on Audio DMA channel 0.  Unlike the Next's
 * Covox, the channel has a REAL volume register, so snd_creature()'s
 * distance attenuation finally works on 8-bit hardware.
 *
 * Placement: the channel's top-address compare is 16-bit, so a sample
 * must never cross a 64K page (a documented MEGA65 audio DMA
 * limitation).  Free regions with the ROM copy ($20000-$3FFFF), our
 * program (bank 0), the C65 DOS ($10000-$11FFF) and the bitmap/matrix
 * ($18000-$1A3FF) avoided:
 *   $40000-$5FFFF   banks 4+5, 128K
 *   $12000-$17FFF   bank-1 gap below the bitmap, 24K
 * The loader first-fits each sample, skipping to the next 64K page or
 * region when it would cross either boundary.
 */
#include <stdint.h>
#include <mega65/fileio.h>

#include "platform.h"
#include "sfx_index65.h"

#define SFX_COUNT (sizeof SFX_INDEX / sizeof SFX_INDEX[0])
#define SFX_NAME  "DAGGOR65.SFX"

/* 24-bit phase step per 40.5 MHz tick: rate / 40.5e6 * 2^24, rounded */
#define SFX_STEP ((uint32_t)((((uint64_t)SFX_RATE << 24) + 20250000ull) \
                             / 40500000ull))

#define POKE(a, v) (*(volatile uint8_t *)(uint16_t)(a) = (uint8_t)(v))
#define PEEK(a)    (*(volatile uint8_t *)(uint16_t)(a))

/* Audio DMA channel 0 register block */
#define AUD_EN      0xD711u  /* bit 7: audio DMA master enable         */
#define CH0_CTRL    0xD720u  /* b7 en, b6 loop, b5 unsigned, b3 stopped,
                                b0-1 format (2 = 8-bit)                */
#define CH0_BASE    0xD721u  /* 24-bit base (loop reload)              */
#define CH0_FREQ    0xD724u  /* 24-bit phase step                      */
#define CH0_TOP     0xD727u  /* 16-bit top-address compare             */
#define CH0_VOL     0xD729u  /* 0..255                                 */
#define CH0_CUR     0xD72Au  /* 24-bit current address (live pointer)  */

static uint32_t sfx_addr[SFX_COUNT];  /* chip-RAM address per sample */
static uint8_t  snd_ok;               /* blob loaded and placed      */

/* from plat_mega65.c; the framebuffer doubles as the load-time bounce
 * buffer - snd_load_blob() runs before the first draw and plat_init
 * clears it afterwards */
extern void plat_lcopy(uint32_t src, uint32_t dst, uint16_t n);
extern uint8_t *const plat_init_bounce;

static uint8_t place_samples(void)
{
    static const uint32_t reg_start[2] = { 0x40000ul, 0x12000ul };
    static const uint32_t reg_end[2]   = { 0x60000ul, 0x18000ul };
    uint8_t  r = 0;
    uint32_t cur = reg_start[0];
    uint8_t  i;

    for (i = 0; i < SFX_COUNT; ++i) {
        uint16_t len = SFX_INDEX[i].len;
        for (;;) {
            uint32_t page_end = (cur | 0xFFFFul) + 1u;
            if (cur + len <= page_end && cur + len <= reg_end[r]) {
                break;                     /* fits here */
            }
            if (page_end < reg_end[r]) {
                cur = page_end;            /* skip to next 64K page */
            } else {
                if (++r >= 2u) {
                    return 0;              /* blob doesn't fit */
                }
                cur = reg_start[r];
            }
        }
        sfx_addr[i] = cur;
        cur += len;
    }
    return 1;
}

void snd_load_blob(void)
{
    uint8_t *buf = plat_init_bounce;
    uint32_t pos = 0;          /* cursor into the blob stream */
    uint8_t  i = 0;            /* sample the cursor is inside */
    uint8_t  fd;

    fd = open(SFX_NAME);
    if (fd == 0xFFu) {
        return;                /* no blob on the SD: play silently */
    }
    if (!place_samples()) {
        close(fd);
        return;
    }
    for (;;) {
        uint16_t got = (uint16_t)read512(buf);
        uint16_t used = 0;
        if (got == 0) {
            break;
        }
        while (used < got && i < SFX_COUNT) {
            uint32_t sam_off = SFX_INDEX[i].off;
            uint16_t sam_len = SFX_INDEX[i].len;
            uint16_t into = (uint16_t)(pos - sam_off);
            uint16_t n = (uint16_t)(sam_len - into);
            if (n > (uint16_t)(got - used)) {
                n = (uint16_t)(got - used);
            }
            plat_lcopy((uint32_t)(uintptr_t)&buf[used],
                       sfx_addr[i] + into, n);
            pos += n;
            used += n;
            if (pos == sam_off + sam_len) {
                ++i;
            }
        }
        if (i >= SFX_COUNT) {
            break;
        }
    }
    close(fd);
    snd_ok = (uint8_t)(pos == SFX_BLOB_LEN);
    POKE(AUD_EN, 0x80);        /* audio DMA master enable */
}

/* one channel, play preempts - the CoCo had a single DAC */
void plat_sound_play(uint8_t sound_id, uint8_t volume)
{
    uint32_t a;
    uint16_t top;

    if (!snd_ok || sound_id >= SFX_COUNT) {
        return;
    }
    a = sfx_addr[sound_id];
    top = (uint16_t)(a + SFX_INDEX[sound_id].len);

    POKE(CH0_CTRL, 0x00);                       /* stop + reconfigure */
    POKE(CH0_CUR + 0, (uint8_t)a);
    POKE(CH0_CUR + 1, (uint8_t)(a >> 8));
    POKE(CH0_CUR + 2, (uint8_t)(a >> 16));
    POKE(CH0_BASE + 0, (uint8_t)a);             /* unused (no loop),  */
    POKE(CH0_BASE + 1, (uint8_t)(a >> 8));      /* kept coherent      */
    POKE(CH0_BASE + 2, (uint8_t)(a >> 16));
    POKE(CH0_FREQ + 0, (uint8_t)SFX_STEP);
    POKE(CH0_FREQ + 1, (uint8_t)(SFX_STEP >> 8));
    POKE(CH0_FREQ + 2, (uint8_t)(SFX_STEP >> 16));
    POKE(CH0_TOP + 0, (uint8_t)top);
    POKE(CH0_TOP + 1, (uint8_t)(top >> 8));
    POKE(CH0_VOL, volume);
    POKE(CH0_CTRL, 0xA2u);     /* enable | unsigned->signed | 8-bit */
}

void plat_sound_stop(void)
{
    POKE(CH0_CTRL, 0x00);
}

uint8_t plat_sound_playing(void)
{
    uint8_t c = PEEK(CH0_CTRL);
    return (uint8_t)((c & 0x80u) != 0 && (c & 0x08u) == 0);
}
