/* probe.c - Dave-chip hardware probe for the Daggorath Enterprise port.
 *
 * Answers the Phase-4 sound unknowns EMPIRICALLY on the machine (emulator
 * now, real EP128 later - the same .com runs on both):
 *
 *   E0-E3  sound-interrupt RATE for each source select:
 *          1 kHz, 50 Hz, tone-0 at n=2499 / n=1249 (discriminates the
 *          250000/(n+1) doc formula from an f/2 reading), and tone-0 at
 *          n=33 with both DAC bits set (the PCM configuration: proves the
 *          oscillator keeps interrupting in DAC mode, at ~7353/s).
 *   E4     EXOS fn-24 free-segment inventory (raw status/segment pairs).
 *   E6     VRAM stretch factor: 1Hz-gated read throughput on a page-0
 *          buffer vs segments FFh and FCh through the P1 window.
 *   E7     blob-safety: for each non-mapped segment F8h-FBh, fill it with
 *          0xE5 through the P1 window, then check EXDOS can still open and
 *          correctly read A:PROBEDAT.BIN.  A segment that survives is safe
 *          for the loader to stash PCM sample data in.
 *
 * The (f) unknown - EXOS's write-only A7h/B4h conventions - is captured
 * host-side: the probe waits ~10s before touching any Dave register
 * ("SNAP NOW"), during which run.sh takes a quick snapshot whose
 * DAVE_STATE chunk is decoded by parse_dave.py.
 *
 * Runs under the STOCK z88dk enterprise crt0 (EXOS VIDEO/KEYBOARD channels
 * -> printf); results are read off the runcom.sh screenshot.
 */
#pragma output noprotectmsdos

#include <stdio.h>
#include <stdint.h>

/* probe_asm.asm */
extern volatile uint8_t  meas_a7;
extern volatile uint16_t meas_frq, meas_count;
extern volatile uint16_t stretch_base, stretch_count;
extern volatile uint8_t  pg_val;
extern volatile uint8_t  ex_chan, ex_status, ex_seg;
extern volatile uint16_t ex_bound, ex_buf, ex_len;
extern void meas_rate(void);
extern void stretch_run(void);
extern void snap_wait(void);
extern void stack_to_p0(void);
extern void fast_mode(void);
extern uint8_t rd_b0(void);
extern uint8_t rd_b1(void);
extern uint8_t rd_b2(void);
extern uint8_t rd_b3(void);
extern uint8_t rd_b4(void);
extern void wr_b1(void);
extern void exos_open_dat(void);
extern void exos_close(void);
extern void exos_read(void);
extern void exos_alloc(void);
extern void exos_free(void);

#define DAT_CHAN 10u

static uint8_t rbuf[512];
static uint8_t p0ref[256];

/* open + read + verify the first 512 bytes of A:PROBEDAT.BIN
 * (pattern (i & 0xFF) ^ 0xA7, generated by run.sh).  1 = intact. */
static uint8_t dat_check(void)
{
    uint16_t i;
    uint8_t st;

    ex_chan = DAT_CHAN;
    exos_open_dat();
    if (ex_status != 0) {
        printf("(OPEN %X) ", ex_status);
        return 0;
    }
    ex_buf = (uint16_t)rbuf;
    ex_len = 512u;
    exos_read();
    st = ex_status;
    ex_chan = DAT_CHAN;
    exos_close();
    if (st != 0) {
        printf("(READ %X) ", st);
        return 0;
    }
    for (i = 0; i != 512u; ++i) {
        if (rbuf[i] != (uint8_t)((i & 0xFFu) ^ 0xA7u)) {
            printf("(DATA @%u) ", i);
            return 0;
        }
    }
    return 1;
}

/* fill one 16K segment with 0xE5 through the P1 window (DI would be
 * kinder to EXOS, but a crash here is itself a result: it identifies a
 * segment EXOS's interrupt path depends on). */
static void fill_seg(uint8_t seg)
{
    volatile uint8_t *p = (volatile uint8_t *)0x4000;
    uint16_t n = 0x4000u;
    uint8_t sv = rd_b1();

    pg_val = seg;
    wr_b1();
    while (n--) {
        *p++ = 0xE5u;
    }
    pg_val = sv;
    wr_b1();
}

static void rate_line(const char *tag, uint8_t a7, uint16_t frq)
{
    meas_a7 = a7;
    meas_frq = frq;
    meas_rate();
    printf("%s: %u\n", tag, meas_count);
}

static void probe_main(void)
{
    uint8_t m0, m1, m2, m3;
    uint8_t seg;

    printf("DAGGORATH DAVE PROBE\n");
    m0 = rd_b0();
    m1 = rd_b1();
    m2 = rd_b2();
    m3 = rd_b3();
    printf("MAP %X %X %X %X B4R=%X\n", m0, m1, m2, m3, rd_b4());

    /* host snapshot window: no Dave writes until this returns */
    printf("SNAP NOW +10S\n");
    snap_wait();
    printf("SNAP DONE\n");

    fast_mode();

    /* EXDOS baseline before anything else touches allocation state */
    printf("DAT BASE: %s\n", dat_check() ? "OK" : "BAD");

    /* E4: segment inventory */
    {
        uint8_t got[12];
        uint8_t n = 0;
        printf("ALLOC:");
        while (n < 12u) {
            exos_alloc();
            printf(" %X/%X", ex_status, ex_seg);
            if (ex_status != 0) {
                break;
            }
            got[n++] = ex_seg;
        }
        printf("\n");
        if (ex_status == 0x7Fu) {       /* .SHARE: boundary matters */
            printf("SHARE BOUND=%X\n", ex_bound);
            exos_free();    /* ex_seg still holds the shared segment; keeping
                             * it starves EXOS of channel RAM (.NORAM opens) */
        }
        while (n) {
            ex_seg = got[--n];
            exos_free();
        }
        printf("DAT POST-ALLOC: %s\n", dat_check() ? "OK" : "BAD");
    }

    /* E0-E3: interrupt rates (counts per exactly one 1Hz-gated second) */
    rate_line("RATE 1KHZ", 0x00u, 0u);
    rate_line("RATE 50HZ", 0x20u, 0u);
    rate_line("RATE TG0 N2499", 0x40u, 2499u);
    rate_line("RATE TG0 N1249", 0x40u, 1249u);
    rate_line("RATE TG0 N33 DAC", 0x58u, 33u);

    /* E6: VRAM stretch (16-read blocks per second) */
    stretch_base = (uint16_t)p0ref;
    stretch_run();
    printf("STRETCH P0: %u\n", stretch_count);
    {
        uint16_t sff, sfc;
        uint8_t sv = rd_b1();
        pg_val = 0xFFu;
        wr_b1();
        stretch_base = 0x4000u;
        stretch_run();
        sff = stretch_count;
        pg_val = 0xFCu;
        wr_b1();
        stretch_run();
        sfc = stretch_count;
        pg_val = sv;
        wr_b1();
        printf("STRETCH FF: %u\n", sff);
        printf("STRETCH FC: %u\n", sfc);
    }

    /* E7: which of F8-FB can hold the PCM blob without killing EXDOS */
    for (seg = 0xF8u; seg <= 0xFBu; ++seg) {
        if (seg == m0 || seg == m1 || seg == m2 || seg == m3) {
            printf("TRASH %X: SKIP (MAPPED)\n", seg);
            continue;
        }
        printf("TRASH %X: ", seg);
        fill_seg(seg);
        printf("EXDOS %s\n", dat_check() ? "OK" : "BAD");
    }

    printf("EP-PROBE DONE\n");
    for (;;) {
        /* idle under EI so the host can snapshot the post-probe state */
    }
}

int main(void)
{
    stack_to_p0();
    probe_main();
    return 0;
}
