/* GENERATED by tools/gen_font.py - DO NOT EDIT.
 * Original 5-bit software character set from SWCHAR.ASM
 * (Dungeons of Daggorath, rights-holder-released source).
 * Rows pre-shifted left 2 to center, as COMTXT.ASM does. */
#ifndef DOD_TABLES_FONT_H
#define DOD_TABLES_FONT_H

#include <stdint.h>

#define FONT_NORMAL_COUNT 31
#define FONT_SPECIAL_COUNT 4
#define FONT_SPECIAL_BASE 0x20

extern const uint8_t FONT_NORMAL[31][7];
extern const uint8_t FONT_SPECIAL[4][7];

#endif /* DOD_TABLES_FONT_H */
