/* GENERATED by tools/gen_vectables.py - DO NOT EDIT.
 * Shape data from the original Dungeons of Daggorath
 * (rights-holder-released), via the C++ port's tables,
 * cross-verified against the original 6809 source. */
#ifndef DOD_TABLES_VEC_H
#define DOD_TABLES_VEC_H

#include <stdint.h>

extern const uint8_t SP_VLA[39];
extern const uint8_t WR_VLA[42];
extern const uint8_t SC_VLA[41];
extern const uint8_t BL_VLA[66];
extern const uint8_t GL_VLA[141];
extern const uint8_t VI_VLA[65];
extern const uint8_t S1_VLA[130];
extern const uint8_t S2_VLA[126];
extern const uint8_t K1_VLA[153];
extern const uint8_t K2_VLA[149];
extern const uint8_t W0_VLA[133];
extern const uint8_t W1_VLA[199];
extern const uint8_t W2_VLA[185];
extern const uint8_t LAD_VLA[56];
extern const uint8_t HUP_VLA[29];
extern const uint8_t HDN_VLA[19];
extern const uint8_t CEI_VLA[6];
extern const uint8_t LPK_VLA[12];
extern const uint8_t RPK_VLA[12];
extern const uint8_t FSD_VLA[8];
extern const uint8_t LSD_VLA[8];
extern const uint8_t RSD_VLA[8];
extern const uint8_t RWAL_VLA[10];
extern const uint8_t LWAL_VLA[10];
extern const uint8_t FWAL_VLA[11];
extern const uint8_t RPAS_VLA[15];
extern const uint8_t LPAS_VLA[15];
extern const uint8_t FPAS_VLA[1];
extern const uint8_t RDOR_VLA[24];
extern const uint8_t LDOR_VLA[24];
extern const uint8_t FDOR_VLA[25];
extern const uint8_t SHIE_VLA[14];
extern const uint8_t SWOR_VLA[11];
extern const uint8_t TORC_VLA[10];
extern const uint8_t RING_VLA[12];
extern const uint8_t SCRO_VLA[12];
extern const uint8_t FLAS_VLA[10];

extern const uint8_t VEC_SCALE[21];
extern const uint8_t VEC_LINES[11];

#endif /* DOD_TABLES_VEC_H */
