/* GENERATED by tools/gen_text.py - DO NOT EDIT.
 * 5-bit packed strings from the original ROM (via the C++
 * port's transcription); decode at runtime with text5.c. */
#ifndef DOD_TABLES_TEXT_H
#define DOD_TABLES_TEXT_H

#include <stdint.h>

extern const uint8_t TXT_ENOUGH1[21];
extern const uint8_t TXT_ENOUGH2[20];
extern const uint8_t TXT_WINNER1[21];
extern const uint8_t TXT_WINNER2[17];
extern const uint8_t TXT_DEATH[21];
extern const uint8_t TXT_COPYRIGHT[21];
extern const uint8_t TXT_WELCOME1[14];
extern const uint8_t TXT_WELCOME2[20];
extern const uint8_t TXT_PREPARE[6];
extern const uint8_t TXT_EXAM1[9];
extern const uint8_t TXT_EXAM2[8];
extern const uint8_t TXT_EXAM3[7];
extern const uint8_t TXT_EXPS[3];

#endif /* DOD_TABLES_TEXT_H */
