/* corpus_gen_ep.c - deterministic line-request corpus for the EP z80
 * draw identity test (tests/z80draw-ep).
 *
 * Categories 1-7 are byte-identical to tests/z80draw/corpus_gen.c (the
 * Next's corpus; same PRNG, same seed 0xC0DE1234) so the EP rasterizer
 * faces everything the Next's did.  Category 8 is EP-directed: the
 * enterprise/draw_ep.asm horizontal/vertical solid-line fast paths are
 * claimed to be candidate-set IDENTITIES with the generic DDA, so this
 * block hammers exactly their dispatch conditions - full-width
 * clear-screen rows (normal and inverse, both directions), single
 * columns at every byte boundary, spans clipped by each edge, spans
 * entirely off-screen, sub-byte spans, and axis-aligned lines that must
 * NOT take the fast path (period > 1).
 *
 * PRNG: xorshift32, fixed seed 0xC0DE1234.  Category 8 sits after the
 * PRNG mix so categories 1-7 replay the identical stream.
 */
#include <stdio.h>
#include <stdint.h>

static uint32_t prng_state = 0xC0DE1234u;

static uint32_t xs32(void)
{
    uint32_t x = prng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    prng_state = x;
    return x;
}

static const uint8_t fadset[8] = { 0, 1, 2, 4, 8, 16, 32, 0xFF };

static unsigned n_emitted = 0;

static void emit(int x0, int y0, int x1, int y1, unsigned fad, unsigned flags)
{
    printf("    { %6d, %6d, %6d, %6d, 0x%02X, 0x%02X },\n",
           x0, y0, x1, y1, fad & 0xFFu, flags & 0xFFu);
    ++n_emitted;
}

/* random coordinate in [-512, 767] */
static int rc(void) { return (int)(xs32() % 1280u) - 512; }

int main(void)
{
    int i, d, f, m;

    printf("/* GENERATED by corpus_gen_ep.c - do not edit.  Seed 0xC0DE1234. */\n");
    printf("typedef struct {\n"
           "    int16_t x0, y0, x1, y1;\n"
           "    uint8_t vctfad, flags;\n"
           "} corpus_rec;\n\n");
    printf("static const corpus_rec corpus[] = {\n");

    /* 1. sixteen directions from screen centre, all fade values,
     *    normal and inverse: 16*8*2 = 256 */
    {
        static const int dir[16][2] = {
            { 60,   0}, { 60,  25}, { 60,  60}, { 25,  60},
            {  0,  60}, {-25,  60}, {-60,  60}, {-60,  25},
            {-60,   0}, {-60, -25}, {-60, -60}, {-25, -60},
            {  0, -60}, { 25, -60}, { 60, -25}, { 25, -25}
        };
        for (d = 0; d < 16; ++d)
            for (f = 0; f < 8; ++f)
                for (m = 0; m < 2; ++m)
                    emit(128, 96, 128 + dir[d][0], 96 + dir[d][1],
                         fadset[f], m);
    }

    /* 2. axis/diagonal exact lengths incl. 1 (single pixel candidate)
     *    and 0 (nothing), solid + a faded twin: 8 dirs * 9 lens * 2 +
     *    zero-length block */
    {
        static const int u[8][2] = {
            {1,0},{1,1},{0,1},{-1,1},{-1,0},{-1,-1},{0,-1},{1,-1}
        };
        static const int lens[9] = { 1, 2, 3, 5, 7, 8, 9, 255, 256 };
        for (d = 0; d < 8; ++d)
            for (i = 0; i < 9; ++i) {
                int L = lens[i];
                emit(120, 90, 120 + u[d][0]*L, 90 + u[d][1]*L, 0, 0);
                emit(121, 91, 121 + u[d][0]*L, 91 + u[d][1]*L,
                     fadset[(d + i) & 7], (unsigned)(d & 1));
            }
        /* zero-length: on-screen, off-screen, all fades */
        for (f = 0; f < 8; ++f) {
            emit(10 + f, 20, 10 + f, 20, fadset[f], 0);
            emit(-100, -100, -100, -100, fadset[f], 1);
        }
        emit(300, 100, 300, 100, 0, 0);
        emit(128, 500, 128, 500, 0, 1);
        emit(0, 0, 0, 0, 0, 0);
        emit(255, 191, 255, 191, 0, 0);
    }

    /* 3. partially clipped: on-screen anchor to a point past each edge,
     *    40 per edge = 160 */
    for (i = 0; i < 40; ++i) {
        int ax = 8 + i * 6;          /* 8..242 */
        int ay = 5 + (i * 9) % 180;  /* 5..175-ish */
        unsigned fad = fadset[i & 7];
        emit(ax, ay, -200 + i * 3, ay + 40 - i, fad, i & 1);        /* left  */
        emit(ax, ay, 500 - i * 2, ay - 30 + i, fad, (i >> 1) & 1);  /* right */
        emit(ax, ay, ax + 25 - i, -180 + i * 2, fad, i & 1);        /* top   */
        emit(ax, ay, ax - 25 + i, 420 - i * 3, fad, (i >> 1) & 1);  /* bottom*/
    }

    /* 4. fully off-screen: both endpoints beyond one edge (candidate
     *    positions interpolate monotonically, so never visible): 80 */
    for (i = 0; i < 20; ++i) {
        unsigned fad = fadset[(i + 3) & 7];
        emit(-512 + i, -400 + i * 7, -3 - i * 2, 300 - i * 9, fad, i & 1);
        emit(258 + i * 5, -450 + i * 11, 767 - i, 500 - i * 13, fad, i & 1);
        emit(-500 + i * 30, -510 + i * 2, 700 - i * 25, -2 - i, fad, i & 1);
        emit(-480 + i * 28, 194 + i, 720 - i * 23, 690 - i * 3, fad, i & 1);
    }

    /* 5. max-length: |delta| up to ~700 crossing the screen: 40 */
    for (i = 0; i < 10; ++i) {
        emit(-350 + i * 4, -60 + i * 5, 350 - i * 3, 250 - i * 4,
             fadset[i & 7], i & 1);
        emit(400 - i * 6, 300 - i * 2, -300 + i * 5, -110 + i * 3,
             fadset[(i + 1) & 7], (i >> 1) & 1);
        emit(-512, 96 - i * 9, 767, 96 + i * 9, fadset[(i + 2) & 7], i & 1);
        emit(128 - i * 7, -512 + i, 128 + i * 7, 191 + i * 40,
             fadset[(i + 5) & 7], (i >> 1) & 1);
    }

    /* 6. flags upper-bit garbage: only bit 0 is PLAT_LINE_INVERSE: 16 */
    for (i = 0; i < 8; ++i) {
        emit(30, 30 + i * 4, 220, 150 - i * 4, fadset[i & 7], 0xFEu);
        emit(30, 32 + i * 4, 220, 152 - i * 4, fadset[i & 7], 0x81u);
    }

    /* 7. PRNG mix: 2000 */
    for (i = 0; i < 2000; ++i) {
        int x0 = rc(), y0 = rc(), x1 = rc(), y1 = rc();
        unsigned fad = (xs32() % 10u < 7u) ? fadset[xs32() & 7u]
                                           : (xs32() & 0xFFu);
        unsigned flags = xs32() & 1u;
        emit(x0, y0, x1, y1, fad, flags);
    }

    /* 8. EP-directed: the H/V solid fast paths (draw_ep.asm) --------- */

    /* 8a. the viewer_clear_screen shape: full-width solid rows at every
     *     y, set and inverse (the inverse ones over rows the set ones
     *     painted white - observable clears): 384 */
    for (i = 0; i < 192; ++i) {
        emit(0, i, 256, i, 0, 0);
        emit(0, i, 256, i, 0, (i & 3) == 1);  /* every 4th row recleared */
    }

    /* 8b. reversed-direction rows, spot rows off both vertical edges */
    for (i = 0; i < 12; ++i) {
        emit(256, i * 16, 0, i * 16, 0, i & 1);       /* sx=- full width  */
        emit(255, i * 16 + 5, -1, i * 16 + 5, 0, 0);  /* on-screen ends   */
    }
    emit(-50, -1, 300, -1, 0, 0);     /* row just above the screen: none */
    emit(-50, 192, 300, 192, 0, 0);   /* row just below: none            */
    emit(-50, -100, 300, -100, 0, 1);
    emit(-50, 400, 300, 400, 0, 1);

    /* 8c. rows clipped by the left/right edges, both directions */
    for (i = 0; i < 16; ++i) {
        emit(-30 - i, 10 + i * 4, 40 + i * 3, 10 + i * 4, 0, i & 1);
        emit(200 + i * 5, 12 + i * 4, 320 + i, 12 + i * 4, 0, (i >> 1) & 1);
        emit(320 + i, 14 + i * 4, 200 - i * 5, 14 + i * 4, 0, i & 1);
        emit(40 + i * 3, 8 + i * 4, -30 - i, 8 + i * 4, 0, (i >> 1) & 1);
    }
    /* rows entirely off one side (empty after clip) */
    emit(-200, 50, -3, 50, 0, 0);
    emit(-3, 51, -200, 51, 0, 1);
    emit(258, 52, 700, 52, 0, 0);
    emit(700, 53, 258, 53, 0, 1);

    /* 8d. sub-byte and byte-boundary spans (lb==hb and lb+1==hb) */
    for (i = 0; i < 8; ++i) {
        emit(i, 100, i + 1, 100, 0, 0);           /* single pixel      */
        emit(i * 8 + 3, 101, i * 8 + 6, 101, 0, 0);   /* inside a byte */
        emit(i * 8 + 5, 102, i * 8 + 11, 102, 0, 0);  /* spans 2 bytes */
        emit(i * 8, 103, i * 8 + 8, 103, 0, i & 1);   /* exact byte    */
        emit(i * 8 + 7, 104, i * 8 + 9, 104, 0, 0);   /* straddles     */
    }
    emit(248, 105, 256, 105, 0, 0);   /* last byte exactly */
    emit(250, 106, 255, 106, 0, 0);   /* right-partial only (hi=254) */
    emit(0, 107, 5, 107, 0, 0);       /* left-partial only */

    /* 8e. single columns at every byte boundary and screen edge, both
     *     directions, set and inverse; clipped and off-screen columns */
    for (i = 0; i < 8; ++i) {
        int x = i * 32 + (i & 7);
        emit(x, 0, x, 192, 0, 0);                 /* full column       */
        emit(x + 9, 192, x + 9, 0, 0, 1);         /* sy=- inverse      */
    }
    emit(0, 0, 0, 192, 0, 0);
    emit(255, 0, 255, 192, 0, 0);
    emit(7, -40, 7, 250, 0, 0);       /* clipped both ends */
    emit(8, 250, 8, -40, 0, 1);
    emit(9, -40, 9, -2, 0, 0);        /* entirely above: none */
    emit(10, 194, 10, 400, 0, 0);     /* entirely below: none */
    emit(-1, 0, -1, 192, 0, 0);       /* off-screen column: none */
    emit(256, 0, 256, 192, 0, 0);
    for (i = 0; i < 12; ++i) {        /* short columns everywhere */
        emit(20 + i * 19, 30 + i * 5, 20 + i * 19, 30 + i * 5 + 1 + i, 0,
             i & 1);
    }

    /* 8f. axis-aligned but FADED (period > 1): must dispatch to the
     *     generic DDA, not the fast paths */
    for (f = 1; f < 8; ++f) {
        emit(0, 110 + f, 256, 110 + f, fadset[f], 0);
        emit(120, 0, 120, 192, fadset[f], f & 1);
        emit(256, 120 + f, 0, 120 + f, fadset[f], 1);
        emit(121, 192, 121, 0, fadset[f], 0);
    }

    /* 9. EP-directed: the solid non-axis OCTANT fast paths ----------- */

    /* 9a. bounds-hugging solid lines: endpoints touching each screen
     *     edge/corner in all octants (worst case for the "candidates
     *     stay in the endpoint bounding box" proof), both parities */
    emit(0, 0, 255, 191, 0, 0);       /* corner-to-corner x-major */
    emit(255, 191, 0, 0, 0, 1);
    emit(0, 191, 255, 0, 0, 0);
    emit(255, 0, 0, 191, 0, 1);
    emit(0, 0, 191, 191, 0, 0);       /* perfect diagonals on edges */
    emit(191, 191, 0, 0, 0, 1);
    emit(64, 191, 255, 0, 0, 0);
    emit(255, 0, 64, 191, 0, 1);
    emit(0, 0, 255, 1, 0, 0);         /* hugging y=0 (x-major) */
    emit(255, 1, 0, 0, 0, 0);
    emit(0, 191, 255, 190, 0, 1);     /* hugging y=191 */
    emit(0, 0, 1, 191, 0, 0);         /* hugging x=0 (y-major) */
    emit(1, 191, 0, 0, 0, 0);
    emit(255, 0, 254, 191, 0, 1);     /* hugging x=255 */

    /* 9b. dispatch boundary: exactly one coordinate one past the
     *     in-bounds box (must fall back to the clipping generic DDA) */
    emit(0, 0, 256, 190, 0, 0);
    emit(256, 190, 0, 0, 0, 0);
    emit(0, 0, 254, 192, 0, 1);
    emit(-1, 5, 254, 188, 0, 0);
    emit(3, -1, 250, 189, 0, 0);
    emit(5, 191, 250, -1, 0, 1);

    /* 9c. byte-boundary and mask-wrap stress: short solid diagonals
     *     crossing x = 8k in all four direction combos */
    for (i = 0; i < 8; ++i) {
        int bx = i * 32 + 6;
        emit(bx, 20 + i * 8, bx + 5, 23 + i * 8, 0, 0);   /* +x +y */
        emit(bx + 5, 40 + i * 8, bx, 44 + i * 8, 0, 0);   /* -x +y */
        emit(bx, 90 + i * 8, bx + 4, 86 + i * 8, 0, 1);   /* +x -y */
        emit(bx + 4, 130 + i * 8, bx, 124 + i * 8, 0, 0); /* -x -y */
    }

    /* 9d. steep/shallow extremes: qy/qx near 1 and near max */
    emit(0, 50, 255, 51, 0, 0);       /* qy = 1 */
    emit(255, 53, 0, 52, 0, 0);
    emit(10, 0, 12, 191, 0, 0);       /* qx = 2 */
    emit(100, 0, 199, 191, 0, 1);     /* qx mid */
    emit(0, 60, 191, 155, 0, 0);      /* adx = 2*ady near-diag */
    emit(128, 96, 255, 160, 0, 0);    /* qy = 129-ish */

    printf("};\n\n#define CORPUS_COUNT %uu\n", n_emitted);
    fprintf(stderr, "corpus_gen_ep: %u records\n", n_emitted);
    return 0;
}
