/* wrapper.c - z80-side test wrapper for the EP rasterizer, compiled
 * with zsdcc for the z88dk "+test" target (org 0x8000, run under
 * z88dk-ticks -mz80: plain Z80, proving draw_ep.asm uses no Z80n
 * opcodes).
 *
 * Replays the compiled-in corpus (corpus_data.h, generated by
 * corpus_gen_ep.c) through the routine under test into a 6144-byte
 * LINEAR framebuffer at 0x4000 (32-byte stride - the exact layout the
 * EP backend uses; only the base differs from the hardware's video
 * segment, and the routine takes the base from draw_base at runtime
 * exactly as it does on hardware).
 *
 * The routine under test provides the symbol plat_draw_line_asm:
 *   - enterprise/draw_ep.asm  (the real EP rasterizer), or
 *   - cref_ep.c               (zsdcc-compiled C DDA, for a cycle
 *                              baseline and a second cross-check)
 *
 * draw_ep.asm reads two backend globals, both provided here:
 *   draw_base  - framebuffer base (plat_ep.c owns it on hardware)
 *   ep_tbl_pg  - lookup-table page block; repointed from its hardware
 *                home 0xF0 to 0x58 (0x5800-0x5AFF, between the
 *                framebuffer and this wrapper's 0x8000 code) BEFORE the
 *                first draw call, as draw_ep.asm requires.
 *
 * Exit protocol: the framebuffer is prefilled with a deterministic
 * pattern (so inverse-mode CLEARS are observable), a completion
 * sentinel is written at 0x5B00/0x5B01, then test_done (done.asm) is
 * reached; run.sh points z88dk-ticks -end at that symbol and collects
 * the RAM image via -output.
 */
#include <stdint.h>
#include "corpus_data.h"

extern void plat_draw_line_asm(int16_t x0, int16_t y0, int16_t x1, int16_t y1,
                               uint8_t vctfad, uint8_t flags);
extern void test_done(void);
extern uint8_t ep_tbl_pg;

uint8_t *draw_base = (uint8_t *)0x4000;

#define FB ((uint8_t *)0x4000)
#define SENTINEL ((volatile uint8_t *)0x5B00)

int main(void)
{
    uint16_t i;

    ep_tbl_pg = 0x58;

    /* deterministic prefill - host_check.c replicates this formula */
    for (i = 0; i < 6144u; ++i) {
        FB[i] = (uint8_t)((uint8_t)(i & 0xFFu) ^ (uint8_t)(i >> 8) ^ 0x5Au);
    }

#ifndef CORPUS_START
#define CORPUS_START 0u
#endif
#ifndef CORPUS_END
#define CORPUS_END CORPUS_COUNT
#endif
    for (i = CORPUS_START; i < CORPUS_END; ++i) {
        /* progress word: current corpus index, for post-mortem reads of
         * partial runs (never part of the compared framebuffer) */
        SENTINEL[2] = (uint8_t)(i & 0xFFu);
        SENTINEL[3] = (uint8_t)(i >> 8);
        plat_draw_line_asm(corpus[i].x0, corpus[i].y0,
                           corpus[i].x1, corpus[i].y1,
                           corpus[i].vctfad, corpus[i].flags);
    }

    SENTINEL[0] = 0xC5u;
    SENTINEL[1] = 0x5Cu;
    test_done();
    return 0;
}
