/* generated by tools/gen_sfxbin.py - do not edit.
 * Offsets into the SFX blob (unsigned 8-bit, 11025 Hz),
 * indexed by sound_ids.h order. */
#define SFX_BLOB_LEN 203237u
#define SFX_RATE 11025u
static const struct { uint32_t off; uint16_t len; }
SFX_INDEX[26] = {
    {      0u,   336u },  /* 00_squeak */
    {    336u,  6096u },  /* 01_rattle */
    {   6432u, 15232u },  /* 02_growl */
    {  21664u,  5920u },  /* 03_beoop */
    {  27584u,  2360u },  /* 04_klank */
    {  29944u, 17024u },  /* 05_grawl */
    {  46968u,  1448u },  /* 06_pssst */
    {  48416u,  3136u },  /* 07_kklank */
    {  51552u,   724u },  /* 08_pssht */
    {  52276u, 20288u },  /* 09_snarl */
    {  72564u, 20224u },  /* 0A_bdlbdl */
    {  92788u, 20224u },  /* 0B_bdlbdl */
    { 113012u,  8195u },  /* 0C_gluglg */
    { 121207u,  5856u },  /* 0D_phaser */
    { 127063u,  7616u },  /* 0E_whoop */
    { 134679u,  5440u },  /* 0F_clang */
    { 140119u,  1984u },  /* 10_whoosh */
    { 142103u,   928u },  /* 11_chuck */
    { 143031u,  1360u },  /* 12_klink */
    { 144391u,  2816u },  /* 13_clank */
    { 147207u,  2800u },  /* 14_thud */
    { 150007u, 15488u },  /* 15_bang */
    { 165495u, 15616u },  /* 16_kaboom */
    { 181111u,    38u },  /* 17_heart */
    { 181149u,    38u },  /* 18_heart */
    { 181187u, 22050u },  /* 19_buzz */
};
