/* corpus_gen.c - deterministic line-request corpus for the z80 draw
 * identity test.  Writes corpus_data.h (a compiled-in C array) to
 * stdout; the SAME generated file is included by both the zsdcc test
 * wrapper (wrapper.c) and the gcc reference checker (host_check.c), so
 * both sides replay byte-identical requests.
 *
 * PRNG: xorshift32, fixed seed 0xC0DE1234 (documented invariant - do
 * not change without regenerating any recorded expectations).
 *
 * Categories (see emit calls in main):
 *   1. all 16 octant/axis directions x 8 vctfad values x normal/inverse
 *   2. axis-aligned and exact-diagonal lines of assorted lengths,
 *      including single-pixel (length 1) and zero-length
 *   3. partially clipped lines crossing each screen edge (x and y)
 *   4. fully off-screen lines (left/right/top/bottom/far corners)
 *   5. max-length lines, |delta| up to ~700
 *   6. flags with garbage upper bits (only bit 0 may matter)
 *   7. PRNG mix: coords in [-512,767], vctfad from the required set
 *      {0,1,2,4,8,16,32,0xFF} plus raw random bytes, random inverse
 */
#include <stdio.h>
#include <stdint.h>

static uint32_t prng_state = 0xC0DE1234u;

static uint32_t xs32(void)
{
    uint32_t x = prng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    prng_state = x;
    return x;
}

static const uint8_t fadset[8] = { 0, 1, 2, 4, 8, 16, 32, 0xFF };

static unsigned n_emitted = 0;

static void emit(int x0, int y0, int x1, int y1, unsigned fad, unsigned flags)
{
    printf("    { %6d, %6d, %6d, %6d, 0x%02X, 0x%02X },\n",
           x0, y0, x1, y1, fad & 0xFFu, flags & 0xFFu);
    ++n_emitted;
}

/* random coordinate in [-512, 767] */
static int rc(void) { return (int)(xs32() % 1280u) - 512; }

int main(void)
{
    int i, d, f, m;

    printf("/* GENERATED by corpus_gen.c - do not edit.  Seed 0xC0DE1234. */\n");
    printf("typedef struct {\n"
           "    int16_t x0, y0, x1, y1;\n"
           "    uint8_t vctfad, flags;\n"
           "} corpus_rec;\n\n");
    printf("static const corpus_rec corpus[] = {\n");

    /* 1. sixteen directions from screen centre, all fade values,
     *    normal and inverse: 16*8*2 = 256 */
    {
        static const int dir[16][2] = {
            { 60,   0}, { 60,  25}, { 60,  60}, { 25,  60},
            {  0,  60}, {-25,  60}, {-60,  60}, {-60,  25},
            {-60,   0}, {-60, -25}, {-60, -60}, {-25, -60},
            {  0, -60}, { 25, -60}, { 60, -25}, { 25, -25}
        };
        for (d = 0; d < 16; ++d)
            for (f = 0; f < 8; ++f)
                for (m = 0; m < 2; ++m)
                    emit(128, 96, 128 + dir[d][0], 96 + dir[d][1],
                         fadset[f], m);
    }

    /* 2. axis/diagonal exact lengths incl. 1 (single pixel candidate)
     *    and 0 (nothing), solid + a faded twin: 8 dirs * 9 lens * 2 +
     *    zero-length block */
    {
        static const int u[8][2] = {
            {1,0},{1,1},{0,1},{-1,1},{-1,0},{-1,-1},{0,-1},{1,-1}
        };
        static const int lens[9] = { 1, 2, 3, 5, 7, 8, 9, 255, 256 };
        for (d = 0; d < 8; ++d)
            for (i = 0; i < 9; ++i) {
                int L = lens[i];
                emit(120, 90, 120 + u[d][0]*L, 90 + u[d][1]*L, 0, 0);
                emit(121, 91, 121 + u[d][0]*L, 91 + u[d][1]*L,
                     fadset[(d + i) & 7], (unsigned)(d & 1));
            }
        /* zero-length: on-screen, off-screen, all fades */
        for (f = 0; f < 8; ++f) {
            emit(10 + f, 20, 10 + f, 20, fadset[f], 0);
            emit(-100, -100, -100, -100, fadset[f], 1);
        }
        emit(300, 100, 300, 100, 0, 0);
        emit(128, 500, 128, 500, 0, 1);
        emit(0, 0, 0, 0, 0, 0);
        emit(255, 191, 255, 191, 0, 0);
    }

    /* 3. partially clipped: on-screen anchor to a point past each edge,
     *    40 per edge = 160 */
    for (i = 0; i < 40; ++i) {
        int ax = 8 + i * 6;          /* 8..242 */
        int ay = 5 + (i * 9) % 180;  /* 5..175-ish */
        unsigned fad = fadset[i & 7];
        emit(ax, ay, -200 + i * 3, ay + 40 - i, fad, i & 1);        /* left  */
        emit(ax, ay, 500 - i * 2, ay - 30 + i, fad, (i >> 1) & 1);  /* right */
        emit(ax, ay, ax + 25 - i, -180 + i * 2, fad, i & 1);        /* top   */
        emit(ax, ay, ax - 25 + i, 420 - i * 3, fad, (i >> 1) & 1);  /* bottom*/
    }

    /* 4. fully off-screen: both endpoints beyond one edge (candidate
     *    positions interpolate monotonically, so never visible): 80 */
    for (i = 0; i < 20; ++i) {
        unsigned fad = fadset[(i + 3) & 7];
        emit(-512 + i, -400 + i * 7, -3 - i * 2, 300 - i * 9, fad, i & 1);
        emit(258 + i * 5, -450 + i * 11, 767 - i, 500 - i * 13, fad, i & 1);
        emit(-500 + i * 30, -510 + i * 2, 700 - i * 25, -2 - i, fad, i & 1);
        emit(-480 + i * 28, 194 + i, 720 - i * 23, 690 - i * 3, fad, i & 1);
    }

    /* 5. max-length: |delta| up to ~700 crossing the screen: 40 */
    for (i = 0; i < 10; ++i) {
        emit(-350 + i * 4, -60 + i * 5, 350 - i * 3, 250 - i * 4,
             fadset[i & 7], i & 1);
        emit(400 - i * 6, 300 - i * 2, -300 + i * 5, -110 + i * 3,
             fadset[(i + 1) & 7], (i >> 1) & 1);
        emit(-512, 96 - i * 9, 767, 96 + i * 9, fadset[(i + 2) & 7], i & 1);
        emit(128 - i * 7, -512 + i, 128 + i * 7, 191 + i * 40,
             fadset[(i + 5) & 7], (i >> 1) & 1);
    }

    /* 6. flags upper-bit garbage: only bit 0 is PLAT_LINE_INVERSE: 16 */
    for (i = 0; i < 8; ++i) {
        emit(30, 30 + i * 4, 220, 150 - i * 4, fadset[i & 7], 0xFEu);
        emit(30, 32 + i * 4, 220, 152 - i * 4, fadset[i & 7], 0x81u);
    }

    /* 7. PRNG mix: 2000 */
    for (i = 0; i < 2000; ++i) {
        int x0 = rc(), y0 = rc(), x1 = rc(), y1 = rc();
        unsigned fad = (xs32() % 10u < 7u) ? fadset[xs32() & 7u]
                                           : (xs32() & 0xFFu);
        unsigned flags = xs32() & 1u;
        emit(x0, y0, x1, y1, fad, flags);
    }

    printf("};\n\n#define CORPUS_COUNT %uu\n", n_emitted);
    fprintf(stderr, "corpus_gen: %u records\n", n_emitted);
    return 0;
}
