/* wrapper.c - z80n-side test wrapper, compiled with zsdcc for the
 * z88dk "+test" target (org 0x8000, run under z88dk-ticks -mz80n).
 *
 * Replays the compiled-in corpus (corpus_data.h, generated by
 * corpus_gen.c) through the routine under test into a 6144-byte buffer
 * at 0x4000 that stands in for the ULA bitmap - the exact address and
 * thirds-interleave layout the real rasterizer uses on hardware.
 *
 * The routine under test provides the symbol plat_draw_line_asm:
 *   - spectrum-next/draw_z80n.asm  (the real Z80n rasterizer), or
 *   - cref_z80.c                   (zsdcc-compiled C DDA, for a cycle
 *                                   baseline and a second cross-check)
 *
 * Exit protocol: the framebuffer is prefilled with a deterministic
 * pattern (so inverse-mode CLEARS are observable), a completion
 * sentinel is written at 0x5B00/0x5B01, then test_done (done.asm) is
 * reached; run.sh points z88dk-ticks -end at that symbol and collects
 * the RAM image via -output.
 */
#include <stdint.h>
#include "corpus_data.h"

extern void plat_draw_line_asm(int16_t x0, int16_t y0, int16_t x1, int16_t y1,
                               uint8_t vctfad, uint8_t flags);
extern void test_done(void);

#define FB ((uint8_t *)0x4000)
#define SENTINEL ((volatile uint8_t *)0x5B00)

int main(void)
{
    uint16_t i;

    /* deterministic prefill - host_check.c replicates this formula */
    for (i = 0; i < 6144u; ++i) {
        FB[i] = (uint8_t)((uint8_t)(i & 0xFFu) ^ (uint8_t)(i >> 8) ^ 0x5Au);
    }

#ifndef CORPUS_START
#define CORPUS_START 0u
#endif
#ifndef CORPUS_END
#define CORPUS_END CORPUS_COUNT
#endif
    for (i = CORPUS_START; i < CORPUS_END; ++i) {
        /* progress word: current corpus index, for post-mortem reads of
         * partial runs (never part of the compared framebuffer) */
        SENTINEL[2] = (uint8_t)(i & 0xFFu);
        SENTINEL[3] = (uint8_t)(i >> 8);
        plat_draw_line_asm(corpus[i].x0, corpus[i].y0,
                           corpus[i].x1, corpus[i].y1,
                           corpus[i].vctfad, corpus[i].flags);
    }

    SENTINEL[0] = 0xC5u;
    SENTINEL[1] = 0x5Cu;
    test_done();
    return 0;
}
