; loader.s - Dungeons of Daggorath, Enterprise 64/128 big-program loader.
;
; WHY: EXOS loads a type-5 .com into a single ~16 KB user segment (page 0,
; Z80 0x0100-0x3FFF).  Our game is 34.5 KB (Z80 0x0100-0x87E1, three
; segments) so a plain .com only ever gets its first 16 KB into RAM.  This
; small loader (which DOES fit page 0) reads the rest of the game image off
; disk into RAM, loads the PCM sample blob, and enters the game's crt0.
;
; SEGMENTS (probe-corrected, PHASE4-DAVE-PROBE.md): from a loaded
; application's context EXOS fn 24 DOES allocate segments on a stock EP128 -
; F9/FA/FB (non-video) then FC/FD/FE (video), then offers FF shared (which
; must NOT be taken: holding the shared segment starves EXOS of channel RAM
; and every later open fails .NORAM).  We allocate everything at startup:
; that both yields the SFX blob segments AND officially reserves FC/FD/FE
; (the game's code pages) so no EXDOS buffer can land there mid-load.
;
; PLAN:
;   * EXOS loads THIS at 0x0100 (P0 = F8h on a stock 128), IRQs on, EXOS
;     alive with its system segment in P3 (0xC000-0xFFFF).
;   * Allocate every free segment (fn 24) until refused; free a .SHARE grant
;     immediately.  Segments < FCh become SFX blob bins.
;   * Open GAME.BIN on channel 1, read the three game pages into FC/FD/FE
;     through the *P1* window (0x4000-0x7FFF): page the target segment into
;     P1, EXOS fn 6 read-block into the window (EXOS works through P3, so
;     P1 survives - proven).  Close.
;   * SFX blob: with >= 8 spare segments try DAGGOR2.SFX (expanded RAM,
;     everything full-rate); else with >= 3 try DAGGOR1.SFX (stock: 3
;     segments + the F8 tail above this loader + the FE tail above the game
;     BSS).  Bin byte counts come from sfx_bins.inc (generated by
;     tools/gen_sfxep.py).  Any open/read failure -> profile 0 (silent
;     game) - never a fatal boot error.
;   * Write the handoff block (profile, seg count, seg list) into the game's
;     page-0 segment at 0x00F0 (below the game image; sound_ep.c reads it).
;   * DI (EXOS now dead - we own the machine).
;   * Copy a tiny trampoline into FF (already in P3) high, clear of the
;     framebuffer/LPT, and run it from there.  Running from P3 lets it repage
;     P0/P1/P2 (FC/FD/FE) without pulling the rug from under itself, then
;     JP 0x0100 into the game crt0.  plat_init then reclaims FF for video.
;
; Build: sjasmplus loader.s --raw=loader.com   (emits header+body from 0x00F0)

GAME_ORG    EQU 0x0100
GAME_P0LEN  EQU 0x4000 - GAME_ORG      ; 0x3F00  (page-0 bytes: game 0x0100..0x3FFF)
GAME_P1LEN  EQU 0x4000                 ; page-1 bytes: game 0x4000..0x7FFF
    INCLUDE "sizes.inc"                ; defines GAME_P2LEN (page-2 remainder)
    INCLUDE "sfx_bins.inc"             ; SFX1_BIN0..4 / SFX2_BIN0..7 byte counts

SEG_P0      EQU 0xFC                   ; game code page 0  -> Z80 P0 at run time
SEG_P1      EQU 0xFD                   ; game code page 1  -> Z80 P1 at run time
SEG_P2      EQU 0xFE                   ; game code page 2  -> Z80 P2 at run time
SEG_VID     EQU 0xFF                   ; video / EXOS system segment (P3)

WIN         EQU 0x4000                 ; P1 load window base (0x4000-0x7FFF)
PORT_P0     EQU 0xB0
PORT_P1     EQU 0xB1
PORT_P3     EQU 0xB3
TRAMP_DST   EQU 0xFF00                 ; where the trampoline runs (in FF/P3),
                                       ; above framebuffer (C000) and LPT (F800)

    MACRO EXOS n
    rst 0x30
    db n
    ENDM

    ORG 0x00F0
; ---- EXOS type-5 module header (16 bytes) ----
    db 0x00, 0x05
    dw codeEnd - main                  ; module body length
    dw 0,0,0,0,0,0

main:                                  ; 0x0100
    di
    ld sp, 0x0FE0                      ; loader stack, page 0, below the window
    ei                                 ; EXOS calls expect interrupts on (midiplay)

    in a, (PORT_P0)                    ; this loader's own segment (F8 on a
    ld (loader_seg), a                 ; stock 128) - its 0x1000-0x3FFF tail
                                       ; is an SFX bin; the game needs the
                                       ; number to fetch from it

    ; ---- allocate every free segment (EXOS fn 24) ----
    ; Yields the SFX bins (segments < FCh) and officially reserves the
    ; game's code pages FC/FD/FE before any file I/O.  A .SHARE grant
    ; (status 0x7F, C = EXOS's shared system segment) is freed at once:
    ; holding it starves EXOS of channel RAM (probe lesson - every later
    ; open would fail .NORAM).
alloc_loop:
    EXOS 24
    or a
    jr z, alloc_got
    cp 0x7F                            ; .SHARE?
    jr nz, alloc_done
    ld (share_bound), de               ; EXOS boundary inside the shared
                                       ; segment (gates the save stash)
    EXOS 25                            ; free it (C = segment)
    jr alloc_done
alloc_got:
    ld a, (seg_cnt)
    cp 16
    jr nc, alloc_loop                  ; list full: hold the grant anyway and
                                       ; KEEP asking - stopping early on a big
                                       ; expanded machine could leave FC/FD/FE
                                       ; unreserved for EXDOS to grab mid-load
    ld e, a
    ld d, 0
    ld hl, seg_list
    add hl, de
    ld (hl), c
    inc a
    ld (seg_cnt), a
    jr alloc_loop
alloc_done:

    ; ---- blob candidates: allocated segments below FCh (max 8) ----
    ld hl, seg_list
    ld de, cand_list
    ld a, (seg_cnt)
    or a
    jr z, cand_done
    ld b, a
cand_loop:
    ld a, (hl)
    cp 0xFC
    jr nc, cand_next                   ; FC-FF: game/video, not a bin
    ld c, a
    ld a, (cand_cnt)
    cp 8
    jr nc, cand_next
    inc a
    ld (cand_cnt), a
    ld a, c
    ld (de), a
    inc de
cand_next:
    inc hl
    djnz cand_loop
cand_done:

    ; ---- open GAME.BIN on channel 1 ----
    ld a, 1
    ld de, fname
    EXOS 1
    or a
    jp nz, fail

    ; ---- read page 0 (game 0x0100-0x3FFF) into FC @ WIN+0x100 ----
    ; Every read is status-checked: booting a partially-loaded image is
    ; worse than halting with the error border (a truncated GAME.BIN or a
    ; bad sector would otherwise "run" and crash unpredictably).
    ld a, SEG_P0
    out (PORT_P1), a
    ld a, 1
    ld de, WIN + 0x0100
    ld bc, GAME_P0LEN
    EXOS 6
    or a
    jp nz, fail

    ; ---- read page 1 (game 0x4000-0x7FFF) into FD @ WIN ----
    ld a, SEG_P1
    out (PORT_P1), a
    ld a, 1
    ld de, WIN
    ld bc, GAME_P1LEN
    EXOS 6
    or a
    jp nz, fail

    ; ---- read page 2 (game 0x8000..end) into FE @ WIN ----
    ld a, SEG_P2
    out (PORT_P1), a
    ld a, 1
    ld de, WIN
    ld bc, GAME_P2LEN
    EXOS 6
    or a
    jp nz, fail

    ; ---- close the file ----
    ld a, 1
    EXOS 3
    or a
    jp nz, fail

    ; ---- SFX blob (optional: any failure just leaves profile = 0) ----
    ; >= 8 spare segments: DAGGOR2.SFX, everything full-rate, 8 x 16K bins.
    ; >= 3: DAGGOR1.SFX, 3 x 16K bins + the loader-segment tail (offset
    ; 0x1000+) + the FE tail (offset 0x1800+, above the game's LUT slot).
    ; Bin byte counts are baked in from sfx_bins.inc.
    ld a, (cand_cnt)
    cp 8
    jp c, sfx_try1
    ld a, 1
    ld de, sfx2name
    EXOS 1
    or a
    jp nz, sfx_try1                    ; no DAGGOR2.SFX: fall back to stock
    ld hl, cand_list
    ld de, sfx2_lens
    ld b, 8
sfx2_loop:
    push bc
    push hl
    push de
    ld a, (de)
    ld c, a
    inc de
    ld a, (de)
    ld b, a                            ; BC = bin length
    ld a, (hl)                         ; A = target segment
    ld de, WIN
    call read_bin
    pop de
    pop hl
    pop bc
    jp nz, sfx_fail
    inc hl
    inc de
    inc de
    djnz sfx2_loop
    ld a, 1
    EXOS 3
    ld a, 2
    ld (profile), a
    jr sfx_done

sfx_try1:
    ld a, (cand_cnt)
    cp 3
    jr c, sfx_done                     ; not enough RAM: silent game
    ld a, 1
    ld de, sfx1name
    EXOS 1
    or a
    jr nz, sfx_done
    ld a, (cand_list+0)
    ld de, WIN
    ld bc, SFX1_BIN0
    call read_bin
    jr nz, sfx_fail
    ld a, (cand_list+1)
    ld de, WIN
    ld bc, SFX1_BIN1
    call read_bin
    jr nz, sfx_fail
    ld a, (cand_list+2)
    ld de, WIN
    ld bc, SFX1_BIN2
    call read_bin
    jr nz, sfx_fail
    ld a, (loader_seg)                 ; own-segment tail, above this loader
    ld de, WIN + 0x1000
    ld bc, SFX1_BIN3
    call read_bin
    jr nz, sfx_fail
    ld a, SEG_P2                       ; FE tail, above the game BSS + LUTs
    ld de, WIN + 0x1800
    ld bc, SFX1_BIN4
    call read_bin
    jr nz, sfx_fail
    ld a, 1
    EXOS 3
    ld a, 1
    ld (profile), a
    jr sfx_done

sfx_fail:
    ld a, 1
    EXOS 3                             ; close; profile stays 0 (silent)
sfx_done:

    ; ---- saves feasible?  The dance restores segment-FF offsets
    ;      0x1800-0x3FFF; if EXOS's shared-segment boundary sits BELOW
    ;      0x1800 the stash would miss live EXOS state -> disable saves.
    ;      (Boundary unmeasured - .SHARE never reached, e.g. expanded
    ;      machines hitting the 16-segment cap - defaults to enabled:
    ;      the boundary is an EXOS-version constant, 0x1806 on 2.1.) ----
    ld a, 1
    ld (exs_flag), a
    ld hl, (share_bound)
    ld a, h
    or l
    jr z, exs_decided
    ld a, h
    cp 0x18
    jr nc, exs_decided
    xor a
    ld (exs_flag), a
exs_decided:

    ; ---- handoff block for the game: profile, seg count, seg list,
    ;      loader segment, saves flag -> game page-0 segment at 0x00F0 ----
    ld a, SEG_P0
    out (PORT_P1), a
    ld hl, hand_block
    ld de, WIN + 0x00F0
    ld bc, 12
    ldir

    ; ---- own the machine: EXOS is done, no more RST 30h ----
    di
    ld a, SEG_VID
    out (PORT_P3), a                   ; FF into P3.  NOT redundant: EXOS runs
                                       ; the app with P3 = ROM segment 00 and
                                       ; its system segment FF at P2 (probe
                                       ; page map F8 F8 FF 00) - reading
                                       ; 0xD800 before this OUT stashes ROM
                                       ; bytes, which cost a debugging session

    ; ---- EXOS-state stash (Phase 5 saves): copy the system segment's
    ;      EXOS-owned region (FF seg offsets 0x1800-0x3FFF: channel RAM,
    ;      variables, stack - everything the game's video will overwrite)
    ;      into the SAME offsets of this loader's segment.  Done LAST,
    ;      under DI, so the snapshot is the freshest EXOS state; the
    ;      in-game save dance restores it around each file operation. ----
    in a, (PORT_P0)
    out (PORT_P1), a
    ld hl, 0xD800                      ; FF now in P3
    ld de, WIN + 0x1800
    ld bc, 0x2800
    ldir

    ; ---- copy the trampoline into FF@TRAMP_DST and run it there ----
    ld hl, tramp
    ld de, TRAMP_DST
    ld bc, trampEnd - tramp
    ldir
    jp TRAMP_DST                       ; enter trampoline (running from P3/FF)

fail:
    di                                 ; EXOS's video ISR repaints the border
                                       ; from BORD_VID every frame - without
                                       ; DI the error colour lasts <20ms
    out (0x81), a                      ; border = the EXOS error status code
fail_loop:
    jr fail_loop

; read one SFX bin: A = target segment, DE = window dest, BC = byte count.
; Returns Z on success (empty bins succeed trivially).
read_bin:
    out (PORT_P1), a
    ld a, b
    or c
    ret z
    ld a, 1
    EXOS 6
    or a
    ret

; ---- trampoline: assembled here, RUN from TRAMP_DST (P3/FF). No stack. ----
; Segment numbers are fixed constants, so no page-0 reads are needed before
; we page page 0 out.  Map the three game segments and enter the game.
tramp:
    ld a, SEG_P0
    out (PORT_P0), a                   ; FC -> P0 (loader is now gone)
    ld a, SEG_P1
    out (PORT_P0 + 1), a               ; FD -> P1
    ld a, SEG_P2
    out (PORT_P0 + 2), a               ; FE -> P2
    jp GAME_ORG                        ; enter the game crt0 at 0x0100
trampEnd:

fname:
    db 10, "A:GAME.BIN"               ; device prefix required (bare name hits
                                       ; the wrong default device and fails)
sfx1name:
    db 13, "A:DAGGOR1.SFX"
sfx2name:
    db 13, "A:DAGGOR2.SFX"

sfx2_lens:                             ; full-profile bin lengths, file order
    dw SFX2_BIN0, SFX2_BIN1, SFX2_BIN2, SFX2_BIN3
    dw SFX2_BIN4, SFX2_BIN5, SFX2_BIN6, SFX2_BIN7

; state + the 12-byte handoff block copied verbatim to game-P0 0x00F0:
; [0] profile (0 silent / 1 stock / 2 full), [1] candidate count,
; [2..9] allocated bin segments, [10] the loader's own segment (the 0xF8
; bin code in sfx_index_ep.h resolves to it; also holds the save stash),
; [11] saves flag (1 = EXOS-state stash valid, dance allowed).
seg_cnt:    defb 0
seg_list:   defs 16
share_bound: defw 0
hand_block:
profile:    defb 0
cand_cnt:   defb 0
cand_list:  defs 8
loader_seg: defb 0
exs_flag:   defb 0

codeEnd:
