#!/usr/bin/env python3
"""Generate core/tables_text.c: the game's 5-bit packed strings.

Packed format (PARSER.ASM EXPAND / the port's Parser::EXPAND):
consecutive 5-bit fields, MSB first.  Field 0 is a count N; fields 1..N+1
are display codes (0 = space, 1..26 = A..Z, $1B.. specials).  We keep the
strings PACKED in ROM (that is the original's space trick) and decode at
runtime with the C EXPAND in core/text5.c; the decoded ASCII appears here
in comments for review.

Source of bytes: the C++ port's LoadFromHex blobs (transcribed from the
original ROM).  This generator re-decodes every blob and fails if any
produces a non-displayable code, so transcription errors surface.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PORT_SRC = REPO / "../../native-port/DungeonsOfDaggorath/src"
OUT_C = REPO / "core/tables_text.c"
OUT_H = REPO / "core/tables_text.h"

# name in viewer.cpp -> C identifier
TEXTS = {
    "enough1": "TXT_ENOUGH1", "enough2": "TXT_ENOUGH2",
    "winner1": "TXT_WINNER1", "winner2": "TXT_WINNER2",
    "death": "TXT_DEATH", "copyright": "TXT_COPYRIGHT",
    "welcome1": "TXT_WELCOME1", "welcome2": "TXT_WELCOME2",
    "prepstr": "TXT_PREPARE",
    "exam1": "TXT_EXAM1", "exam2": "TXT_EXAM2", "exam3": "TXT_EXAM3",
    "exps": "TXT_EXPS",
}

# display code -> readable char for comments (I_SP=0, letters+64,
# I_BAR=$1C, I_DOT=$1E; others shown as <XX>)
def code_char(c):
    if c == 0x00:
        return " "
    if 1 <= c <= 26:
        return chr(c + 64)
    return {0x1B: "<CR>", 0x1C: "|", 0x1D: "<BS>", 0x1E: ".", 0x1F: "?"}.get(
        c, f"<{c:02X}>")


def parse_port_hex(path):
    text = path.read_text()
    pat = re.compile(
        r'Utils::LoadFromHex\(\s*(\w+)\s*,\s*((?:"[0-9A-Fa-f]*"\s*)+)\)', re.S)
    out = {}
    for name, blob in pat.findall(text):
        out[name] = bytes.fromhex(
            "".join(re.findall(r'"([0-9A-Fa-f]*)"', blob)))
    return out


def decode(packed: bytes):
    """EXPAND: field0 = count N; emit N+1 following 5-bit fields."""
    stream = int.from_bytes(packed, "big")
    total_fields = (len(packed) * 8) // 5

    def field(i):
        shift = len(packed) * 8 - 5 * (i + 1)
        return (stream >> shift) & 0x1F

    n = field(0)
    if n + 2 > total_fields:
        return None
    return [field(i) for i in range(1, n + 2)]


def main():
    blobs = parse_port_hex(PORT_SRC / "viewer.cpp")
    missing = [k for k in TEXTS if k not in blobs]
    if missing:
        sys.exit(f"FATAL: missing text blobs: {missing}")

    decoded = {}
    for name in TEXTS:
        codes = decode(blobs[name])
        if codes is None:
            sys.exit(f"FATAL: {name} count field exceeds blob length")
        txt = "".join(code_char(c) for c in codes)
        decoded[name] = (codes, txt)
        print(f"{TEXTS[name]:14s} ({len(blobs[name]):2d} bytes) \"{txt}\"")

    hdr = ("/* GENERATED by tools/gen_text.py - DO NOT EDIT.\n"
           " * 5-bit packed strings from the original ROM (via the C++\n"
           " * port's transcription); decode at runtime with text5.c. */\n")
    with open(OUT_C, "w") as f:
        f.write(hdr)
        f.write('#include "tables_text.h"\n\n')
        for name, ident in TEXTS.items():
            data = blobs[name]
            _, txt = decoded[name]
            body = ",".join(f"0x{b:02X}" for b in data)
            f.write(f'/* "{txt}" */\n')
            f.write(f"const uint8_t {ident}[{len(data)}] = {{{body}}};\n\n")
    with open(OUT_H, "w") as f:
        f.write(hdr)
        f.write("#ifndef DOD_TABLES_TEXT_H\n#define DOD_TABLES_TEXT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        for name, ident in TEXTS.items():
            f.write(f"extern const uint8_t {ident}[{len(blobs[name])}];\n")
        f.write("\n#endif /* DOD_TABLES_TEXT_H */\n")
    print(f"wrote {OUT_C.name}, {OUT_H.name}")


if __name__ == "__main__":
    main()
