#!/usr/bin/env python3
"""Generate core/tables_font.c from the original SWCHAR.ASM.

Normal glyphs (display codes < $20) are stored packed: five bytes hold a
40-bit stream of eight 5-bit fields.  Field 0 is the EXPAND count (always
%00110 = 6, meaning "emit 7 fields"); fields 1..7 are the seven pixel rows.
The game then shifts each row left twice to center the 5 pixels in the
8-pixel cell (COMTXT.ASM NDPB10) - we bake that shift into the table.

Special glyphs (codes >= $20, SPCTAB) are stored raw: 7 bytes, one row per
byte, used as-is with no centering shift.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ASM = REPO / "../../disassembly/daggorath/original-source/SWCHAR.ASM"
OUT_C = REPO / "core/tables_font.c"
OUT_H = REPO / "core/tables_font.h"

EXPAND_COUNT_HEADER = 0b00110  # field 0 of every packed glyph


def parse_swchar():
    """Return (normal_bytes, special_bytes, names) from SWCHAR.ASM."""
    in_special = False
    normal, special = [], []
    names = {"normal": [], "special": []}
    for raw in ASM.read_text(errors="replace").splitlines():
        if re.match(r"^SPCTAB\b", raw):
            in_special = True
            continue
        code = raw.split(";", 1)[0]
        comment = raw.split(";", 1)[1].strip() if ";" in raw else ""
        m = re.match(r"^\s+FCB\s+%([01]{8})\s*$", code)
        if not m:
            continue
        val = int(m.group(1), 2)
        (special if in_special else normal).append(val)
        if comment:
            key = "special" if in_special else "normal"
            names[key].append(comment)
    return normal, special, names


def unpack_glyph(five: bytes):
    """5 packed bytes -> 7 centered row bytes (row bits in 6..2)."""
    stream = int.from_bytes(bytes(five), "big")  # 40 bits, MSB first
    fields = [(stream >> (35 - 5 * i)) & 0x1F for i in range(8)]
    if fields[0] != EXPAND_COUNT_HEADER:
        sys.exit(f"FATAL: glyph count header {fields[0]:#07b} != %00110")
    return [f << 2 for f in fields[1:8]]


def ascii_art(rows, width=8):
    return [format(r, f"0{width}b").replace("0", ".").replace("1", "#")
            for r in rows]


def main():
    normal_raw, special_raw, names = parse_swchar()
    if len(normal_raw) % 5 or len(special_raw) % 7:
        sys.exit(f"FATAL: byte counts normal={len(normal_raw)} (mod 5) "
                 f"special={len(special_raw)} (mod 7)")
    n_norm = len(normal_raw) // 5
    n_spec = len(special_raw) // 7
    print(f"normal glyphs: {n_norm}, special glyphs: {n_spec}")

    glyphs = [unpack_glyph(normal_raw[i * 5:(i + 1) * 5]) for i in range(n_norm)]
    specials = [special_raw[i * 7:(i + 1) * 7] for i in range(n_spec)]

    # sanity: display code 1 must draw a letter 'A'
    a_rows = [r >> 2 for r in glyphs[1]]
    expect_a = [0b00100, 0b01010, 0b10001, 0b10001, 0b11111, 0b10001, 0b10001]
    if a_rows != expect_a:
        sys.exit(f"FATAL: glyph 1 is not 'A': {[bin(r) for r in a_rows]}")
    print("glyph sanity check: code 1 renders as letter A ✓")

    def glyph_name(kind, idx):
        lst = names[kind]
        per = 5 if kind == "normal" else 7
        i = idx * per
        return lst[i].split("=")[0].strip("* ").strip() if i < len(lst) else "?"

    hdr = ("/* GENERATED by tools/gen_font.py - DO NOT EDIT.\n"
           " * Original 5-bit software character set from SWCHAR.ASM\n"
           " * (Dungeons of Daggorath, rights-holder-released source).\n"
           " * Rows pre-shifted left 2 to center, as COMTXT.ASM does. */\n")
    with open(OUT_C, "w") as f:
        f.write(hdr)
        f.write('#include "tables_font.h"\n\n')
        f.write(f"const uint8_t FONT_NORMAL[{n_norm}][7] = {{\n")
        for i, rows in enumerate(glyphs):
            art = " ".join(ascii_art(rows))
            f.write(f"    /* ${i:02X} {glyph_name('normal', i):<14s}*/ "
                    f"{{{','.join(f'0x{r:02X}' for r in rows)}}},\n")
        f.write("};\n\n")
        f.write(f"const uint8_t FONT_SPECIAL[{n_spec}][7] = {{\n")
        for i, rows in enumerate(specials):
            f.write(f"    /* ${0x20 + i:02X} {glyph_name('special', i):<14s}*/ "
                    f"{{{','.join(f'0x{r:02X}' for r in rows)}}},\n")
        f.write("};\n")
    with open(OUT_H, "w") as f:
        f.write(hdr)
        f.write("#ifndef DOD_TABLES_FONT_H\n#define DOD_TABLES_FONT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FONT_NORMAL_COUNT {n_norm}\n")
        f.write(f"#define FONT_SPECIAL_COUNT {n_spec}\n")
        f.write("#define FONT_SPECIAL_BASE 0x20\n\n")
        f.write(f"extern const uint8_t FONT_NORMAL[{n_norm}][7];\n")
        f.write(f"extern const uint8_t FONT_SPECIAL[{n_spec}][7];\n")
        f.write("\n#endif /* DOD_TABLES_FONT_H */\n")
    print(f"wrote {OUT_C.name}, {OUT_H.name}")
    print("letter A:")
    for line in ascii_art(glyphs[1]):
        print("   ", line)


if __name__ == "__main__":
    main()
