#!/usr/bin/env python3
"""Pack the per-sound .raw files into one SFX blob + index header.

The blob (daggorath.sfx) is a straight concatenation - NO padding or
alignment: samples may cross 8K-page boundaries at arbitrary offsets,
and the players handle that (Next: dma_arm/scale_into_bounce chunking;
MEGA65: place_samples() re-places each sample to dodge 64K crossings).
The generated header maps sound_ids.h order to (offset, length) within
the blob.

usage: gen_sfxbin.py <raw-dir> <out-blob> <out-header> [rate]
(rate defaults to 11025; the MEGA65 blob uses 7350 = 22050/3)
"""
import os
import sys

NAMES = [
    "00_squeak", "01_rattle", "02_growl", "03_beoop", "04_klank",
    "05_grawl", "06_pssst", "07_kklank", "08_pssht", "09_snarl",
    "0A_bdlbdl", "0B_bdlbdl", "0C_gluglg", "0D_phaser", "0E_whoop",
    "0F_clang", "10_whoosh", "11_chuck", "12_klink", "13_clank",
    "14_thud", "15_bang", "16_kaboom", "17_heart", "18_heart",
    "19_buzz",
]

raw_dir, out_blob, out_header = sys.argv[1], sys.argv[2], sys.argv[3]
rate = int(sys.argv[4]) if len(sys.argv) > 4 else 11025

blob = bytearray()
index = []
for name in NAMES:
    data = open(os.path.join(raw_dir, name + ".raw"), "rb").read()
    index.append((name, len(blob), len(data)))
    blob += data

with open(out_blob, "wb") as f:
    f.write(blob)

with open(out_header, "w") as f:
    f.write("/* generated by tools/gen_sfxbin.py - do not edit.\n"
            " * Offsets into the SFX blob (unsigned 8-bit, %u Hz),\n"
            " * indexed by sound_ids.h order. */\n" % rate)
    f.write("#define SFX_BLOB_LEN %uu\n" % len(blob))
    f.write("#define SFX_RATE %uu\n" % rate)
    f.write("static const struct { uint32_t off; uint16_t len; }\n")
    f.write("SFX_INDEX[%d] = {\n" % len(index))
    for name, off, ln in index:
        f.write("    { %6uu, %5uu },  /* %s */\n" % (off, ln, name))
    f.write("};\n")

pages = (len(blob) + 8191) // 8192
print(f"{out_blob}: {len(blob)} bytes ({pages} x 8K pages), "
      f"{len(index)} sounds")
